name: Handle Email Issues

on:
  issues:
    types: [opened]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  handle_email_issues:
    if: startsWith(github.event.issue.title, '[邮箱订阅]')
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
    - name: Handle subscription issue
      uses: actions/github-script@v7
      with:
        script: |
          const issue_number = context.issue.number;
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const login = context.payload.issue.user.login;

          await github.rest.issues.addLabels({
            owner,
            repo,
            issue_number,
            labels: ["subscribed"],
          });

          await github.rest.issues.createComment({
            owner,
            repo,
            issue_number,
            body: `🤩你好呀！ ${login}！你已经成功通过邮件订阅了本站啦！若有新文章将通过邮箱推送给你！谢谢你的订阅！\n😥如果您实在想要关闭订阅，在右下角直接删除这个issue就好！咕咕咕咕咕咕咕！感谢你的订阅！`,
          });

          await github.rest.issues.update({
            owner,
            repo,
            issue_number,
            state: "closed",
          });
